spring:
  application:
    name: employee-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://configserver:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.infinity: DEBUG






#auditevents  , Exposes audit events information for the current application.
#beans  , Displays a complete list of all the Spring beans in your application.
#caches , Exposes available caches.
#conditions , Shows the conditions that were evaluated on configuration and auto-configuration classes and the reasons why they did or did not match.
#configprops  , Displays a collated list of all\u00A0@ConfigurationProperties.
#env  , Exposes properties from Spring\u2019s\u00A0ConfigurableEnvironment.
#flyway , Shows any Flyway database migrations that have been applied.
#health , Shows application health information.
#httptrace  , Displays HTTP trace information (by default, the last 100 HTTP request-response exchanges).
#info , Displays arbitrary application info.
#integrationgraph , Shows the Spring Integration graph.
#loggers  , Shows and modifies the configuration of loggers in the application.
#liquibase  , Shows any Liquibase database migrations that have been applied.
#metrics  , Shows \u2018metrics\u2019 information for the current application.
#mappings , Displays a collated list of all\u00A0@RequestMapping\u00A0paths.
#scheduledtasks , Displays the scheduled tasks in your application.
#sessions , Allows retrieval and deletion of user sessions from a Spring Session-backed session store. Not available when using Spring Session\u2019s support for reactive web applications.
#shutdown , Lets the application be gracefully shutdown.
#threaddump , Performs a thread dump.

#management.endpoints.web.base-path=/

#  io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties
resilience4j.circuitbreaker:
  instances:
    employeeservice:
      registerHealthIndicator: true
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
    organizationService:
      registerHealthIndicator: true
      minimumNumberOfCalls: 6
      permittedNumberOfCallsInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

# rate-limiter config
resilience4j.ratelimiter:
  instances:
    employeeservice:
      limitForPeriod: 5
      limitRefreshPeriod: 5000
      timeoutDuration: 1000ms
#
resilience4j.retry:
  instances:
    retryEmployeeservice:
      maxAttempts: 5
      waitDuration: 10000
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.bulkhead:
  instances:
    bulkheadEmployeeservice:
      maxWaitDuration: 2ms
      maxConcurrentCalls: 20


resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadEmployeeservice:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
